USE ConcisoIT;

CREATE TABLE Routes(
routeID INTEGER UNSIGNED AUTO_INCREMENT,
name VARCHAR(50),
PRIMARY KEY(routeID)
);

CREATE TABLE Stops(
stopID INTEGER UNSIGNED AUTO_INCREMENT,
latit DOUBLE PRECISION,
longi DOUBLE PRECISION,
PRIMARY KEY(stopID)
);

CREATE TABLE Buses(
busID INTEGER UNSIGNED AUTO_INCREMENT,
licensePlate VARCHAR(7),
routeFK INTEGER UNSIGNED,
PRIMARY KEY(busID),
INDEX FK_route(routeFK),
FOREIGN KEY(routeFK) REFERENCES Routes(routeID)
);

CREATE TABLE RELATIONS(
relationsID INTEGER UNSIGNED AUTO_INCREMENT,
routeID INTEGER UNSIGNED,
stopID INTEGER UNSIGNED,
INDEX FK_route(routeID),
INDEX FK_stop(stopID),
FOREIGN KEY(routeID) REFERENCES Routes(routeID),
FOREIGN KEY(stopID) REFERENCES Stops(stopID),
PRIMARY KEY(relationsID)
);